### ISSUE TITLE
Cannot redirect log output - Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by rcbyron** [hey-athena/hey-athena-client#31]
ERROR: "pocketsphinx.c", line 250: Cannot redirect log output
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/athena/__main__.py", line 7, in <module>
    brain.init()
  File "/usr/local/lib/python3.4/dist-packages/athena/brain.py", line 14, in init
    inst = Brain()
  File "/usr/local/lib/python3.4/dist-packages/athena/brain.py", line 28, in __init__
    stt.init()
  File "/usr/local/lib/python3.4/dist-packages/athena/stt.py", line 23, in init
    decoder = Decoder(config)
  File "/usr/local/lib/python3.4/dist-packages/pocketsphinx/pocketsphinx.py", line 271, in __init__
    this = _pocketsphinx.new_Decoder(*args)
RuntimeError: new_Decoder returned -1

**Comment by rcbyron** [comment]
This is a permission error. It is solved by using: "sudo python3"
