### ISSUE TITLE
Wrong AVBin 10 version (32 bit vs 64 bit)

### ISSUE THREAD

**Issue by rcbyron** [hey-athena/hey-athena-client#32]
Unexpected error loading library libavbin.so.10: libavbin.so.10: wrong ELF class: ELFCLASS64
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pyglet/__init__.py", line 351, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'load'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/athena/brain.py", line 202, in run
    text = stt.active_listen()
  File "/usr/local/lib/python3.4/dist-packages/athena/stt.py", line 59, in active_listen
    tts.play_mp3('double-beep.mp3')
  File "/usr/local/lib/python3.4/dist-packages/athena/tts.py", line 28, in play_mp3
    sound = pyglet.resource.media(file_name, streaming=False)
  File "/usr/local/lib/python3.4/dist-packages/pyglet/resource.py", line 629, in media
    return media.load(path, streaming=streaming)
  File "/usr/local/lib/python3.4/dist-packages/pyglet/__init__.py", line 357, in __getattr__
    __import__(import_name)
  File "/usr/local/lib/python3.4/dist-packages/pyglet/media/__init__.py", line 1492, in <module>
    from . import avbin
  File "/usr/local/lib/python3.4/dist-packages/pyglet/media/avbin.py", line 62, in <module>
    av = pyglet.lib.load_library(av)
  File "/usr/local/lib/python3.4/dist-packages/pyglet/lib.py", line 135, in load_library
    lib = ctypes.cdll.LoadLibrary(name)
  File "/usr/lib/python3.4/ctypes/__init__.py", line 429, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.4/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libavbin.so.10: wrong ELF class: ELFCLASS64

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/athena/__main__.py", line 4, in <module>
    brain.inst.run()
  File "/usr/local/lib/python3.4/dist-packages/athena/brain.py", line 217, in run
    raise Exception
Exception

**Comment by rcbyron** [comment]
Fix by switching from 64 bit to 32 bit or vice versa.
