### ISSUE TITLE
Pyglet and AVbin issue

### ISSUE THREAD

**Issue by hell-g** [hey-athena/hey-athena-client#39]
Hi guys,

Just discovered Hey Athena two days ago. Very cool project!
I am using Arch Linux and when I compile AVbin from the Arch User Repository (AUR), I get Hey Athena to start and it reacts on my waking up command. But then immediately, there is an error:

~ Waiting to be woken up... 

~ Active listening... 

~ Something went wrong. Would you like to see the error message?

Unknown Google TTS issue: 'StaticSource' object has no attribute '_data'
Continue? (Y/N) y
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/athena/brain.py", line 225, in run
    text = stt.active_listen()
  File "/usr/lib/python3.5/site-packages/athena/stt.py", line 63, in active_listen
    tts.play_mp3('double-beep.mp3')
  File "/usr/lib/python3.5/site-packages/athena/tts.py", line 29, in play_mp3
    sound.play()
  File "/usr/lib/python3.5/site-packages/pyglet/media/__init__.py", line 472, in play
    player.queue(self)
  File "/usr/lib/python3.5/site-packages/pyglet/media/__init__.py", line 978, in queue
    group.queue(source)
  File "/usr/lib/python3.5/site-packages/pyglet/media/__init__.py", line 695, in queue
    source = source._get_queue_source()
  File "/usr/lib/python3.5/site-packages/pyglet/media/__init__.py", line 622, in _get_queue_source
    return StaticMemorySource(self._data, self.audio_format)
AttributeError: 'StaticSource' object has no attribute '_data'

When I use the binary installer from the AVbin website instead, this error does not occur. Do you have an idea, what my AVbin installation is missing?

Thanks!

**Comment by rcbyron** [comment]
Glad you like our project! We've shifted from working on this client a bit to working on a web demo/service (though we will continue to work on this client as well).

As for your issue, my guess would be that the the AVBin from the Arch User Repository is just outdated. I know this is the case for the Ubuntu/Debian package index. Anyway, is there a particular reason you need to compile AVBin rather than using the binaries?

- Connor

**Comment by hell-g** [comment]
Thank you for your reply. I hope you will be able to continue to work on the client. Would love to see it with more features and to have it running in my apartment. I am having problems though to wake it up. Any recommendations there? Is a good quality microphone necessary? My commands are usually correctly interpreted, but waking up is the hardest part.

The Arch User Repository version is 10-2. It is hard to compare the version numbers, as I don't really see one on the AVBin webpage. Well in my opinion, it is always nicer to have everything installed with the tools your distribution gives you. But as it is quite easy to install and uninstall the binary package, it is not a problem. Just remembering what to remove when you want to uninstall it, will be the challenge. 

Thanks for your work!

**Comment by rcbyron** [comment]
I'm definitely going to work more on the wake-up-trigger part of this. It's buggy on some systems and fine on others. To debug though, you can disable STT in settings.py.

In the mean time:
- Make sure your microphone is set up properly (test recordings)
- Try using a decent quality external USB microphone (I use the Blue Snowball)
- Try saying the wake-up-word (default is "athena") faster or slower
- Try saying the wake-up-word in a higher-pitched voice (seems to register better)

**Comment by hell-g** [comment]
Great, thanks for your help! Looking forward to see more improvements!!

**Comment by AboNawaF474** [comment]
Hello

Please I need help
How can I fix this error

~ Waiting to be woken up... 

~ Active listening... 

~ (runtime error)

~ Something went wrong. Would you like to see the error message?

~ Unknown Google TTS issue: Library "c" not found.
Continue? (Y/N) y

~ Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyglet/__init__.py", line 378, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'unschedule'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/athena/brain.py", line 222, in run
    text = stt.active_listen()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/athena/stt.py", line 66, in active_listen
    tts.play_mp3('double-beep.mp3')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/athena/tts.py", line 51, in play_mp3
    sound.play()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyglet/media/sources/base.py", line 269, in play
    player.queue(self)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyglet/media/player.py", line 103, in queue
    self._set_playing(self._playing)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyglet/media/player.py", line 130, in _set_playing
    pyglet.clock.unschedule(self.update_texture)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyglet/__init__.py", line 384, in __getattr__
    __import__(import_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyglet/clock.py", line 169, in <module>
    _c = pyglet.lib.load_library('c')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyglet/lib.py", line 158, in load_library
    raise ImportError('Library "%s" not found.' % names[0])
ImportError: Library "c" not found.


~ Waiting to be woken up... 


Thanks
